### ISSUE TITLE
If part of the current focus window gets unloaded, we should update the focus window

### ISSUE THREAD

**Issue by jcmorrow** [replayio/devtools#7032] opened 2022-06-01 17:13 UTC
Right now if part of the focus window gets unloaded we will reflect that visually on the timeline, which is great, but we won't update the bounds of the current focus window to reflect it, which means that the user can still seek outside of the loaded regions.

I cannot easily show a recording of this because I can't execute the unload command in the console, but here are repro steps:

- Open a recording
- Focus on the first 2-5 seconds
- Put the playhead in the first second
- Run this in the console: `await app.sendMessage("Session.unloadRegion", {region: {begin: 0, end: 1000}})`
- The first second should unload
- Observe that you can still seek on the timeline to the unloaded area

**Comment by jaril** [comment] 2022-06-03 00:33
@jcmorrow inferred from soft focus being a soft yes for being done by tomorrow as a signal to add this to the current sprint. Lmk if I got that wrong!

**Comment by jaril** [comment] 2022-06-08 15:46
@bvaughn mind picking this up?

**Comment by bvaughn** [comment] 2022-06-08 16:28
> Right now if part of the focus window gets unloaded we will reflect that visually on the timeline, which is great, but we won't update the bounds of the current focus window to reflect it, which means that the user can still seek outside of the loaded regions.

I don't think I see the connection you're making here @jcmorrow. We now explicitly allow you to seek outside of loaded regions (as #6913: Global Loader 1.6) so even if we resized the focus window to fit unloaded regions, it would still be possible to do that.

**Comment by bvaughn** [comment] 2022-06-08 16:41
Here's a Loom showing what I mean:
https://www.loom.com/share/86716b2dd31f4c08a2a0b45e5eb9fe66?from_recorder=1&focus_title=1

I think this is working as intended now (as of #7064).

**Comment by bvaughn** [comment] 2022-06-08 17:25
Going to close this as "working as designed" then. Josh please re-open if I'm mistaken!

**Closed by bvaughn** 2022-06-08 17:25 UTC
Labels: ui polish, feature-focus

**Comment by jcmorrow** [comment] 2022-06-08 17:50
Oh, ha, funny. Yeah, it allowed clicking outside of the window back when that *wasn't* supposed to be allowed, but now that we've changed the rules, it's fine.
